site_name: "Open Science in Practice: Collaborative Research with Git"
site_description: "Course docs for K8F6106 (KI, fall 2026)"
site_url: ""
repo_url: "https://github.com/k-CIR/course-open-science-in-practice.git"
edit_uri: "edit/main/docs/"
docs_dir: docs
extra_css:
  - stylesheets/style.css
extra_javascript:
  - javascripts/slide-gallery.js

theme:
  name: material
  color_mode: auto
  # user_color_mode_toggle: true
  palette:
    # - media: "(prefers-color-scheme)"
    #   primary: black
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Schedule: schedule.md
  - Lectures:
      - lectures/index.md
      - '1. Why Git? Intro and context': lectures/lecture-1-why-git.md
      - '2. Git basics': lectures/git-lectures-basics.md
      - '3. Git remote': lectures/git-lectures-remote.md
      - '4. Git branching': lectures/git-lectures-branching.md
      - '5. Working in an IDE: Positron': lectures/positron-lectures-1.md
      - '6. Markdown and Quarto': lectures/markdown-quarto.md
      - '7. Use AI in your work': lectures/ai-assistance.md
      - '8. Mini project and data overview': lectures/lecture-data-overview.md
      - '9. Git collaboration': lectures/git-lectures-collaboration.md


  - Exercises:
    - exercises/index.md
    - 'Workshops':
      - 'Git #1 - Basics': exercises/git-exercises-basics.md
      - 'Git #2 - Remote': exercises/git-exercises-remote.md
      - 'Git #3 - Branching': exercises/git-exercises-branching.md
      - 'Git #4 - Collaboration': exercises/git-exercises-collaboration.md
      # - 'Testing your scripts': exercises/quality-exercises-1.md
    - 'Project and Examination':
      - 'Your mini-project': project/project-description.md
      - 'Examination seminar': project/project-examination.md
#      - 'Presentation of results': project/project-presentation.md
  - Resources:
    - Before course starts:
      - setup/index.md
      - 'Install Git': setup/git-setup.md
      - 'Setup GitHub': setup/github-setup.md
      - 'Install R': setup/install-r.md
      - 'Setup Positron': setup/positron-setup.md
      - 'Optional: R primer': setup/R-primer.md
    - Simulated data:
      - "Simulated dataset 1": resources/simulated-dataset-1.md
      - "Simulated dataset 2": resources/simulated-dataset-2.md
      - "Simulated dataset 3": resources/simulated-dataset-3.md
      - "Simulated dataset 4": resources/simulated-dataset-4.md
    - Glossary: resources/glossary.md
#    - Git:
#      - 'Git basics': resources/git-basics.md
#      - 'Git remote': resources/git-remote.md
#      - 'Git branching': resources/git-branching.md
#      - 'Git collaboration': resources/git-collaboration.md
#    - Positron:
#      - 'Positron basics': resources/positron-basics.md

#    - External resources:
#      - "Git": resources/git-resources.md
#      - "Positron": resources/positron-resources.md
  
