site_name: "Open Science in Practice: Collaborative Research with Git"
site_description: "Course docs for K8F6106 (KI, fall 2026)"
site_url: ""
repo_url: "https://github.com/k-CIR/course-open-science-in-practice.git"
edit_uri: "edit/main/docs/"
docs_dir: docs
extra_css:
  - stylesheets/style.css
extra_javascript:
  - javascripts/slide-gallery.js

theme:
  name: material
  color_mode: auto
  # user_color_mode_toggle: true
  palette:
    # - media: "(prefers-color-scheme)"
    #   primary: black
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Setup: 
    - setup/index.md
    - "Setup Git": setup/git-setup.md
    - "Setup Positron": setup/positron-setup.md
    - "Setup GitHub": setup/github-setup.md
  - Schedule: schedule.md
  - Lectures:
      - "Overview": lectures/index.md
      - "Lecture 1 - Why git?": lectures/lecture-1-why-git.md
      - 'Git':
        - "Git #1 basics": lectures/git-lectures-1.md
        - "Git #2 branching": lectures/git-lectures-2.md
        - "Git #3 remote": lectures/git-lectures-3.md
        - "Git #4 collaboration": lectures/git-lectures-4.md
      - 'Tools':
        - "Positron #1 basics": lectures/positron-lectures-1.md
        - "Positron #2 extended": lectures/positron-lectures-2.md
        - "R #1 basics": lectures/r-lectures-1.md
        - "Markdown and Quarto": lectures/markdown-quarto.md
        - "Use AI in your work": lectures/agentic-coding.md
  - Exercises:
    - 'Workshops':
      - 'Git #1 basics': 'exercises/git-exercises-1.md'
      - 'Git #2 branching': 'exercises/git-exercises-2.md'
      - 'Git #3 safety': 'exercises/git-exercises-3.md'
      - 'Git #4 collaboration': 'exercises/git-exercises-4.md'
      # - 'Testing your scripts': exercises/quality-exercises-1.md
    - 'Project':
      - "Work on your project": project/project-description.md
      - "Forking": project/project-fork.md
      - "Contribute (Pull request)": project/project-contribute.md
      - "Examination": project/project-examination.md
      - "Presentation of results": project/project-presentation.md
  - Glossary: glossary.md
  - Resources:
    - "External resources":
      - "Overview": resources/external-resources.md
    - "Simulated data":
      - "Simulated dataset 1": resources/simulated-dataset-1.md
      - "Simulated dataset 2": resources/simulated-dataset-2.md
      - "Simulated dataset 3": resources/simulated-dataset-3.md
      - "Simulated dataset 4": resources/simulated-dataset-4.md
  

  # - Days:
  #   - "Day 0 - Precourse": lectures/day-0.md
  #   - "Day 1 - Git & projects": lectures/day-1.md
  #   - "Day 2 - Data & collaboration": lectures/day-2.md
  #   - "Day 3 - Peer work": lectures/day-3.md
  #   - "Day 4 - Support": lectures/day-4.md
  #   - "Day 5 - Examination": lectures/day-5.md
  
